import { Inter } from "next/font/google";
import "./globals.css";
import "@mantine/core/styles.css";
import {
  createTheme,
  MantineProvider,
  MantineColorsTuple,
} from "@mantine/core";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const myColor = [
  "#eaedff",
  "#d2d6ff",
  "#a2aafa",
  "#6f7bf5",
  "#4453f0",
  "#2939ee",
  "#182dee",
  "#0820d5",
  "#001bbf",
  "#0016a9",
];

const theme = createTheme({
  colors: {
    myColor,
  },
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MantineProvider theme={theme}>{children}</MantineProvider>
      </body>
    </html>
  );
}
